#!/usr/bin/env python3
"""
聚合脚本：读 SQLite → 生成 kpis.json
跑完 collect.py 后执行本脚本，产出文件给前端 fetch。
接口通了上 OSS 后，把这个文件 put 到 bucket，前端改 fetch URL 即可。

用法：
  python3 scripts/aggregate.py                # 输出到 kpis.json
  python3 scripts/aggregate.py --out xxx.json # 指定输出路径
"""
from __future__ import annotations
import argparse, json, sqlite3
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DB_PATH = ROOT / "data" / "heatmap.db"
OUT_PATH = ROOT / "kpis.json"


def fetchone(conn, sql, params=()):
    cur = conn.execute(sql, params)
    row = cur.fetchone()
    cols = [c[0] for c in cur.description] if cur.description else []
    return dict(zip(cols, row)) if row else {}


def fetchall(conn, sql, params=()):
    cur = conn.execute(sql, params)
    cols = [c[0] for c in cur.description]
    return [dict(zip(cols, r)) for r in cur.fetchall()]


def build_kpis(conn) -> dict:
    # 1. 最新 llm-data 快照
    live = fetchone(conn, "SELECT * FROM v_latest_llm")
    live_out = {
        "requests_today":       live.get("requests_today", 0),
        "tokens_today":         live.get("tokens_today", 0),
        "requests_yday":        live.get("requests_yday", 0),
        "tokens_yday":          live.get("tokens_yday", 0),
        "requests_change_rate": live.get("requests_change_rate", "0%"),
        "tokens_change_rate":   live.get("tokens_change_rate", "0%"),
    }

    # 2. 最新活跃用户
    users = fetchone(conn, "SELECT * FROM v_latest_users")
    users_out = {
        "distinct_users_30d": users.get("distinct_users_30d", 0),
        "distinct_users_90d": users.get("distinct_users_90d", 0),
        "scope_note":         users.get("scope_note", "仅含 AI-Buddy"),
    }

    # 3. 应用数
    apps = fetchone(conn, "SELECT * FROM v_apps_count")
    apps_out = {
        "total_online":     apps.get("total_online", 0),
        "planned":          apps.get("planned", 0),
        "total":            apps.get("total", 0),
        "delta_this_month": 3,  # 手动维护，暂留 mock；未来可建一张 ops_log 表
    }

    # 4. 本月成本 + 上月对比
    cur_month = fetchone(conn, "SELECT * FROM v_cost_current_month")
    prev_month = fetchone(conn, """
      SELECT COALESCE(SUM(cost_cny), 0) AS cost_cny
      FROM fact_cost_monthly
      WHERE ym = strftime('%Y-%m', 'now', 'localtime', '-1 month')
    """)
    cur_cost = cur_month.get("cost_cny", 0) or 0
    prev_cost = prev_month.get("cost_cny", 0) or 0
    rate = None
    if prev_cost > 0:
        delta = (cur_cost - prev_cost) / prev_cost * 100
        rate = f"{delta:+.2f}%"
    cost_out = {
        "current_month_cny": round(cur_cost, 2),
        "prev_month_cny":    round(prev_cost, 2),
        "change_rate":       rate or "0%",
        "note":              "Azure T+7 / 百炼 T+1，手动录入",
    }

    # 5. 近 7 天趋势
    trend_rows = fetchall(conn, "SELECT t_date, requests FROM v_trend_7d")
    trend_out = {
        "dates":    [r["t_date"][5:].replace("-", "/") for r in trend_rows],  # "05/09"
        "requests": [r["requests"] for r in trend_rows],
    }

    # 6. TOP 5 应用
    top5_rows = fetchall(conn, "SELECT name, requests FROM v_top5_yday")
    total_top5 = sum(r["requests"] for r in top5_rows) or 1
    top5_out = [
        {"name": r["name"], "requests": r["requests"],
         "share": round(r["requests"] / total_top5, 4)}
        for r in top5_rows
    ]

    # 7. 调用平台（昨日 requests + tokens + 当月 cost）
    plat_rows = fetchall(conn, """
      SELECT source AS platform,
             SUM(requests) AS requests,
             SUM(tokens)   AS tokens
      FROM fact_llm_detail
      WHERE t_date = date('now', 'localtime', '-1 day')
        AND source != 'all'
      GROUP BY source
      ORDER BY requests DESC
    """)
    cost_by_platform = {r["platform"]: r["cost_cny"] for r in fetchall(conn, """
      SELECT platform, SUM(cost_cny) AS cost_cny
      FROM fact_cost_monthly
      WHERE ym = strftime('%Y-%m', 'now', 'localtime')
      GROUP BY platform
    """)}
    platforms_out = [
        {"platform": r["platform"],
         "requests": r["requests"],
         "tokens":   r["tokens"],
         "cost_cny": round(cost_by_platform.get(r["platform"], 0), 2)}
        for r in plat_rows
    ]

    return {
        "updated_at": datetime.now().isoformat(timespec="seconds"),
        "note":       "Auto-generated by scripts/aggregate.py from heatmap.db",
        "live":       live_out,
        "users":      users_out,
        "apps":       apps_out,
        "cost":       cost_out,
        "trend_7d":   trend_out,
        "top5_apps":  top5_out,
        "platforms":  platforms_out,
    }


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(OUT_PATH), help="输出 JSON 路径")
    args = ap.parse_args()

    if not DB_PATH.exists():
        raise SystemExit(f"[err] {DB_PATH} 不存在；先跑 sql/01_schema.sql + 02_seed_applications.sql")

    conn = sqlite3.connect(DB_PATH)
    try:
        data = build_kpis(conn)
    finally:
        conn.close()

    out = Path(args.out)
    out.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"[done] {out}  ({len(json.dumps(data))} bytes)")


if __name__ == "__main__":
    main()
